version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/judyapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
